### ISSUE TITLE
我用它做了求职辅助，体验很好~

### ISSUE THREAD

**Issue by Raynox77** [yzfly/LangGPT#3]
有两个问题请教一下：
1. 怎么让提示词轻松迭代，更加符合用户的心意？能否增加提示词迭代的功能？
2. 在一条对话记录中，如果聊的时间久了，是否GPT会忘记前面的信息？有什么方法可以不用重开一条对话，反复使用同一个提示词而不受其他聊天内容的污染？

**Comment by yzfly** [comment]
1. 有考虑，LangGPT 的稳定迭代范式目前在探索中，个人迭代可以参考吴恩达的 prompt 课程中的迭代方法。
2. 过长会忘记，可以使用 reminder 缓解这一问题。不重开对话的情况下，可以使用指令：“请忘记上述内容”。通过 API 的方式也可以做到避免污染问题。

目前手头上的事情比较多，LangGPT 项目需要探索和稳定实现的方面也较多，工作比较繁重，有意参与请提交 pr

**Comment by Raynox77** [comment]
感谢回复，很有帮助！ 
问个小白问题，这个模板的使用需要把这个页面中的内容全部复制下来（包括举的例子）吗？https://raw.githubusercontent.com/yzfly/LangGPT/main/LangGPTHelper.md

还是只需要把提示词主文复制下来（如下）？
# Role: Your_Role_Name

## Profile

- Author: YZFly
- Version: 0.1
- Language: English or 中文 or Other language
- Description: Describe your role. Give an overview of the character's characteristics and skills

### Skill-1
1.技能描述1
2.技能描述2

### Skill-2
1.技能描述1
2.技能描述2

## Rules
1. Don't break character under any circumstance.
2. Don't talk nonsense and make up facts.

## Workflow
1. First, xxx
2. Then, xxx
3. Finally, xxx

## Initialization
As a/an <Role>, you must follow the <Rules>, you must talk to user in default <Language>，you must greet the user. Then introduce yourself and introduce the <Workflow>.

**Comment by yzfly** [comment]
全部复制性能会比较稳定，后面看看能不能缩短优化一下

**Comment by zmcmcc** [comment]
我的理解或者说尝试的感受是，如果全部复制下来，chatgpt基本会扮演LangGPT，把readme的一些概念再复述一遍？如果只复制role的代码，则会立刻进入角色扮演？

**Comment by yzfly** [comment]
是的

**Comment by Raynox77** [comment]
我喜欢全部复制下来，因为有这些例子，只需要告诉GPT我要扮演什么角色，它就能自动补充那些<skills><rules><workflow>，而且准确度很高，非常智能。如果只复制主文，那么这些变量都要自己去填写，这样不够智能。

**Comment by zmcmcc** [comment]
不过如果你要做一些精细的角色扮演，那么角色的一些设定的变量本来就是得手动写的吧。如果只是要有一个大概角色，那倒是没问题

**Comment by yzfly** [comment]
分享我目前的工作流：
1. LangGPT 帮写一个 prompt，达到要求，结束。
2. 若未达到要求，手动 or 给 LangGPT 一些指令迭代微调（告诉它调整方向即可）
